#!/bin/bash

MYPATH=$(realpath $0)
DIR=$(dirname $MYPATH)

CODESPELL=$(which codespell)
if [ $? -ne 0 ]; then
	echo "codespell not installed - unable to check spelling" >&1
	exit
fi

$CODESPELL -I $DIR/ignore-list $1
exit 0
