#!/bin/bash

MYPATH=$(realpath $0)
DIR=$(dirname $MYPATH)

ASPELL=$(which aspell)
if [ $? -ne 0 ]; then
	echo "aspell not installed - unable to check spelling" >&1
	exit
fi

WORDS=$(grep -v 'Fixes\|Signed-off-by\|Reviewed-by\|Tested-by' $1 | \
	$ASPELL --extra-dicts $DIR/btrfs-aspell.dat --mode=email \
		--add-email-quote='#' list | sort -u)
if [ -n "$WORDS" ]; then
    printf "\e[1;33m  Possible spelling errors found in commit message:\n\e[0m\e[0;31m%s\n\e[0m\e[1;33m  Use git commit --amend to change the message.\e[0m\n\n" "$WORDS" >&2
fi
