#!/bin/bash

_exit() {
	echo $1
	exit 1
}

_json_escape() {
	printf '%s' "$1" | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
}

[ "$#" -ne 2 ] && _exit "btrfs-create-usage <MSGID> <SUBJECT>"

gh --help > /dev/null
[ $? -ne 0 ] && _exit "Please install gh to use this tool (https://cli.github.com/manual/installation)"

MSG_ID=$1

TEMPLATE="Link to patches

https://lore.kernel.org/linux-btrfs/${MSG_ID}/

b4 am ${MSG_ID}"

read -p "Enter an existing issue to update (enter to create new): " issue

if [ "$issue" == "" ]
then
	gh issue create --title "${2}" --project "Btrfs kernel patch review" \
		-R "btrfs/linux" --body "${TEMPLATE}"
else
	TEMPLATE=$(_json_escape "${TEMPLATE}")
	TITLE=$(_json_escape "${2}")
	echo "{\"body\": ${TEMPLATE}}" |
		gh api "repos/btrfs/linux/issues/${issue}/comments" --input=-
	echo "{\"title\": ${TITLE}}" | \
		gh api "repos/btrfs/linux/issues/${issue}" --input=-

	# Remove label 'update' in case it's a new revision of the patch
	label=update
	repo=btrfs/linux
	gh api -X DELETE "repos/$repo/issues/$issue/labels/$label"
fi
