#!/bin/bash

if [ "$#" -ne 1 ]; then
	echo "Usage: btrfs-setup-git-hooks <git dir>"
	exit 1
fi

TARGET="$1/.git/hooks"

if [ ! -e "$TARGET" ]; then
	echo "Must point at a real git directory"
	exit 1
fi

REALPATH=$(realpath $0)
DIR=$(dirname $REALPATH)

ln -sf $DIR/btrfs-commit-msg $TARGET/commit-msg
ln -sf $DIR/btrfs-commit-msg $TARGET/applypatch-msg
ln -sf $DIR/btrfs-checkpatch $TARGET/pre-commit
ln -sf $DIR/btrfs-checkpatch $TARGET/pre-applypatch
