#!/bin/sh
# finish issue
# - remove for-next
# - add misc-next
# - move to finished column

if [ -z "$1" ]; then
	echo "ERROR: usage: $0 issue"
	exit 1
fi

issue="$1"
repo=btrfs/linux

#
# Delete labels
#
echo "GITHUB: remove labels (for-next, misc-next)"
gh api -X DELETE "repos/$repo/issues/$issue/labe ls/for-next"
gh api -X DELETE "repos/$repo/issues/$issue/labels/misc-next"

#
# Archive card
#

# gh api -H "Accept: application/vnd.github.inertia-preview+json" -X GET "repos/btrfs/linux/projects"
# jq '.[].id'
project=5220516

# gh api -H "Accept: application/vnd.github.inertia-preview+json" -X GET "/projects/5220516/columns"
# jq '.[].id'
column1=10505384
column2=10505389
column3=10505398

# NOTE: old preview API!
card=$(gh api -H "Accept: application/vnd.github.starfox-preview" \
	-X GET "repos/btrfs/linux/issues/$issue/events" | \
	jq ".[0].project_card.id")

# move card to 3d column
echo "GITHUB: archive card $card"
echo '{"archived":true}' |
	gh api -H "Accept: application/vnd.github.inertia-preview+json" \
		-X PATCH "projects/columns/cards/$card" --input=-

#
# Close issue
#
echo "GITHUB: archive card $card"
echo '{"state":"closed"}' |
	gh api -H "Accept: application/vnd.github.inertia-preview+json" \
		-X PATCH "/repos/$repo/issues/$issue" --input=-
