#!/bin/sh
#
# Keep only last week/month worth of CI runs, selected workflows

type -p gh > /dev/null || { echo "ERROR: gh tool not found"; exit 1; }
type -p jq > /dev/null || { echo "ERROR: jq tool not found"; exit 1; }

repo="btrfs/linux"

daysmax=30

clean_workflow() {
	local wf="$1"
	local json=$(gh run -R "$repo" list --limit 500 --workflow "$wf" --json databaseId,startedAt)

	echo "Cleaning workflow $wf"
	i=0
	while :; do
		id=$(echo "$json" | jq -r ".[$i].databaseId")
		if [ "$id" == "null" -o -z "$id" ]; then
			break
		fi
		echo "ID: $id"
		now=$(date +%s)
		date=$(echo "$json" | jq -r ".[$i].startedAt")
		ts=$(date --date=${date} +%s)
		delta=$(($now-$ts))
		days=$(($delta/3600/24))
		echo "Started at $id, delta $delta, days $days"
		if [ "$days" -ge "$daysmax" ]; then
			echo "Delete run $id"
			gh run -R "$repo" delete "$id"
		fi

		# loop
		i=$(($i+1))
	done
}

clean_ids() {
	echo "Cleaning ids $@"
	for id in "$@"; do
		if [ "$id" == "null" -o -z "$id" ]; then
			break
		fi
		echo "ID: $id"
		echo "Delete run $id"
		gh run -R "$repo" delete "$id"
	done
}

clean_workflow "CI"
#clean_workflow "C/C++ CI"

daysmax=7
clean_workflow "Build"

#clean_ids `cat wfs`
